#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: elasticsearch-pvc
#  namespace: elk-stack
#  labels:
#    kubernetes.io/cluster-service: "true"
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 2G
#---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk-stack
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elk-stack
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elastic/elasticsearch:6.8.6
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
#        volumeMounts:
#        - mountPath: /data
#          name: elasticsearch-pvc
#        - mountPath: /usr/share/elasticsearch/config
#          name: elasticsearch-config
#      volumes:
#      - name: elasticsearch-pvc
#        persistentVolumeClaim:
#          claimName: elasticsearch-pvc
#      - name: elasticsearch-config
#        configMap:
#          name: elasticsearch-config
#---
#kind: ConfigMap
#apiVersion: v1
#metadata:
#  name: elasticsearch-config
#  namespace: elk-stack
#data:
#  elasticsearch.yml: |-
#    http.host: 0.0.0.0
#    path.scripts: /tmp/scripts
#  log4j2.properties: |-
#    status = error
#    appender.console.type = Console
#    appender.console.name = console
#    appender.console.layout.type = PatternLayout
#    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n
#    rootLogger.level = info
#    rootLogger.appenderRef.console.ref = console
#  jvm.options: |-
#    -Xms512m
#    -Xmx512m
#    -XX:+UseConcMarkSweepGC
#    -XX:CMSInitiatingOccupancyFraction=75
#    -XX:+UseCMSInitiatingOccupancyOnly
#    -XX:+AlwaysPreTouch
#    -server
#    -Xss1m
#    -Djava.awt.headless=true
#    -Dfile.encoding=UTF-8
#    -Djna.nosys=true
#    -Djdk.io.permissionsUseCanonicalPath=true
#    -Dio.netty.noUnsafe=true
#    -Dio.netty.noKeySetOptimization=true
#    -Dio.netty.recycler.maxCapacityPerThread=0
#    -Dlog4j.shutdownHookEnabled=false
#    -Dlog4j2.disable.jmx=true
#    -Dlog4j.skipJansi=true
#    -XX:+HeapDumpOnOutOfMemoryError