apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
---
apiVersion: v1
data:
  ssh_known_hosts: |
    bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
    gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
    gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
    gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
    ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
    vs-ssh.visualstudio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ssh_known_hosts":"bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==\ngithub.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==\ngitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=\ngitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf\ngitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9\nssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H\nvs-ssh.visualstudio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-ssh-known-hosts-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-ssh-known-hosts-cm","namespace":"argocd"}}
  labels:
    app.kubernetes.io/name: argocd-ssh-known-hosts-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-ssh-known-hosts-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":null,"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-tls-certs-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-tls-certs-cm","namespace":"argocd"}}
  labels:
    app.kubernetes.io/name: argocd-tls-certs-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-tls-certs-cm
---
apiVersion: v1
data:
  admin.password: JDJhJDEwJFFRTlNJSWxBM2pPbjhpRVM1RDkxNk82eEdJR2VRQ2R5Z20xQk1NWkF2VGpMaXFOZFR1YUoy
  admin.passwordMtime: MjAyMC0wOC0zMFQxMTozNjoxMVo=
  server.secretkey: Q05TVmZXbUtHOWtTbythSUIvLzdFMHlOSEl0VjY2VUlCRkNwMDZQUnJvQT0=
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaakNDQWs2Z0F3SUJBZ0lSQUwvSjhKdWxRWmNGYjJqekdrYnk5RG93RFFZSktvWklodmNOQVFFTEJRQXcKRWpFUU1BNEdBMVVFQ2hNSFFYSm5ieUJEUkRBZUZ3MHlNREE0TXpBeE1UTTFNRFphRncweU1UQTRNekF4TVRNMQpNRFphTUJJeEVEQU9CZ05WQkFvVEIwRnlaMjhnUTBRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFDLzYzUkNQWUZaSE11cnpubHNMa3hieTc1Q2RBcU1ldnJsVjhPTmFBMWtWT3ErN0ppS0lKeXkKdHdKcGxVdGIrOEc1WFdOQXVrVTZpbG1RcVlxWXNEblhOcVR1Zy93b2RPcWtJMFZyNkQxNHdMeXhRcGdxb0hLSwpYUUc2VndjVi9VbG5idlhLaWhBNEJFcG1qczV1ZUwwR3FCYzZMNGgzdXVpMGdIVlplQTlKSkQwcGhrL1kyOFlqCjA1SW02STlMMUJoWW5xL3dwM2Ric01RQW1MNGtFQ0prTlZJVFFzb0dKSkc5MUtMYlMvMXl0bU5hT2hqekp6TFkKVitDajJtNGxVMU5MN1Z4dThFcnh4WUJ0K2lUeVFNVW5PUjhwdEU4d3A5dzFoTFZ6bDFyYnFUeUJjUzFYNW1aLwpEaWRGVE5LemN6NW9Bb3lVenVlS0ZJV3NoRmRFSkYxQkFnTUJBQUdqZ2JZd2diTXdEZ1lEVlIwUEFRSC9CQVFECkFnS2tNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3ZXdZRFZSMFIKQkhRd2NvSUpiRzlqWVd4b2IzTjBnZzFoY21kdlkyUXRjMlZ5ZG1WeWdoUmhjbWR2WTJRdGMyVnlkbVZ5TG1GeQpaMjlqWklJWVlYSm5iMk5rTFhObGNuWmxjaTVoY21kdlkyUXVjM1pqZ2laaGNtZHZZMlF0YzJWeWRtVnlMbUZ5CloyOWpaQzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBa0xrL3lBa2IKNGZpN1Y2ZGpReU9SWEpzM0p1akpsQnpxZlFaYkhUaXpPTWN3V1I4Q1F2ZkxGczZoenAxMnJiVnFlZlRRVXJyQQorRE5oNFJpY1dPY1JaRnFlczAwMk1lU2RwR0hhVmdpY1RIeG5lRVZnVGZaTEVTcmVmYjhzbWZwaUZ2RHRpSE9SCk5pdzdxaUxUQVdlL3AyR2RhbjVPZ3hPQ3JuanliaVlEd0NiQkVsZW5uRWkrNEJ2d2l6cytzaUcvakhNWWJpYVYKdDdvZHB5WVdocUYrNU02MTN3b241RENha2l6ck5lR04yNDVMUnExYllEQkhSK2FZTDhGRmJEMHZNaitZdmgyZQpyQWZ5THM1Q2RJay8zd0VXQVZXWHhLRFlUVDBUR3NtblUvcVp0MGd4VXZWeGZLU1l2UTdlRmFBbHA2QnMzVFM2ClAwTzhvSlhVZ3NrdWR3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdit0MFFqMkJXUnpMcTg1NWJDNU1XOHUrUW5RS2pIcjY1VmZEaldnTlpGVHF2dXlZCmlpQ2NzcmNDYVpWTFcvdkJ1VjFqUUxwRk9vcFprS21LbUxBNTF6YWs3b1A4S0hUcXBDTkZhK2c5ZU1DOHNVS1kKS3FCeWlsMEJ1bGNIRmYxSloyNzF5b29RT0FSS1pvN09ibmk5QnFnWE9pK0lkN3JvdElCMVdYZ1BTU1E5S1laUAoyTnZHSTlPU0p1aVBTOVFZV0o2djhLZDNXN0RFQUppK0pCQWlaRFZTRTBMS0JpU1J2ZFNpMjB2OWNyWmpXam9ZCjh5Y3kyRmZnbzlwdUpWTlRTKzFjYnZCSzhjV0FiZm9rOGtERkp6a2ZLYlJQTUtmY05ZUzFjNWRhMjZrOGdYRXQKVitabWZ3NG5SVXpTczNNK2FBS01sTTduaWhTRnJJUlhSQ1JkUVFJREFRQUJBb0lCQVFDTmhZdmllTVpVTnhhOQpaM0ZFWTlPczhVNG9aTGVPcGZVemY0ZFZWQUJrRnZaUHVkbzJLUnhEOFE0WFc1OEpnbGwxWGpjZGVQNHB6L0dCCjZuT29hbk1NajJBSi9rdkliWWJGYUxqOWZIRXdCVGhmb2xMaFJCV1NrRWtBNXNIejVpWGwzdjNpei9KcnpFWXMKNEd1N0xNOS9CQjYwcW02QWs5U2JuZ3BxNGt5clNvVklzcDA3WHcrQTdBQndEZEhsSXRySmZnYnRLTFVkbDVMdgpNamVpY1IybUdKZ1lORXJVbjlzLzZwSnpSWWl6RkN6ZFBBZ29BNTM1Uld3dmxBVmxxdXEwRFpIQ1VndEF1SjVQCnBCUzBEK1NmU0ZtSnNGRXVxUmhOMGJyRmZlcXdHRWQyaFV6S0F0S3ZOZVN5N1pucEdnemhQQU5LbDROTjd5dGsKSk5mL1JIMVJBb0dCQU91V0pVaWJSbkl1Q21GUmIvQkZPcnI2c21vbjFucWtlWUFxYzJYem9wN0l4QnVlMEtPUQpUNFFKckdkaFRRTlRWcS9VTjhER0duTXFoYXJiMVM1R1pkQW4yekRTTWNCMUM5aFF6Zm9zRmZYTUlBTkg2M0lQCnluNy9sVUw3QmE2M0RrWG9LVlV4UDB4MGM3bmNWTmRYcitGS2xIbTZMTDRmNGZhRkJiSjh0L0tOQW9HQkFOQ00KcmJUUGFONXN4bmRRUFNESzZwVWVXZ2VBOUxNaXBxVzdGNC9jRjNjVC9Za210NlVGdys3NXdqU1hTTmpuMDl3TQo3NVJibFA1MURjSmhmY0JhRTVUa1l0UEV4WFlnTnYxR3dsWStGcUpyRzBRT1d6NUdVZTk3NXJRYy8wZzNOdmd4CnZKUCt0cXdFZDBreThoNWhUeitKOXorVFVxMVoyUUh0bENPZTkwS0ZBb0dCQU0rVGx6eFhYSVhrblU3TVk3WXcKT2FSZ21tM0F0bEdQdEdMQ2hMVnpLM2wrNnBSdnBlUklsbGQvOG9HUWtUdjU1V3E5c1haUTF5TmNkelJweUhlaQpuYmtBTlRqYUsrNG84NHZnL3V5TWhiank1ODRjUTQ5WDdKTmovWTlzQU1ER0dIUnVNR1VaSkczb09jT3RLTEFwCldoWkhFWFlFSGNKVDgxUzBOcVhqRUcxTkFvR0FSMWpwa0tNb3VIZTBTbHRzSGt6dGhraVUrbDQyMlJZd3R5QlQKeGtiQXpGOU5iTitQRW1qdmlGRndESGY1VnlPd3ltYXVqQzNzd2tVZmlQRzdpTlFJUVBjRmpIZVVLbjZJOFl1RQpydWFjN2NJQTJQNmtYcURHSlUxWk55TjRmcWROS2dveC90dTBlUk1xRUNQYXkyUDFMY0t3a05LQkJZZG9nNDFaCkVmcXZrdFVDZ1lFQW5RQk96Qjk4WmVQek5tVVNRRUFtOUtBMHloT1J5dWROUDRsdjNTc255Q3Q1TTd4RzNMSGgKL21odzNpM1ZaOEdJSy9Lb1RJKzdka01DODQyWnJEcVROdnVZWWlZYkNUOStqcEd1ZlIzK2tVK0YrdFhoWU1DcApWbVdZVndaS2pIdFdjcHdYd3V5dnFMU1FCbEwwN3BZaVNSU2xYN0VPMXlBd0dVVFJxc2F5TElRPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-secret","app.kubernetes.io/part-of":"argocd"},"name":"argocd-secret","namespace":"argocd"},"type":"Opaque"}
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
type: Opaque
---
apiVersion: v1
data:
  config: eyJiZWFyZXJUb2tlbiI6ImV5SmhiR2NpT2lKU1V6STFOaUlzSW10cFpDSTZJaUo5LmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKaGNtZHZZMlF0YldGdVlXZGxjaTEwYjJ0bGJpMDFabWR5YmlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKaGNtZHZZMlF0YldGdVlXZGxjaUlzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJbUpsTXpneVlqWmhMVEV3T1RndE5HRmhNeTFoTVdZMkxXSTBPRFk0WXpZMk0yUmtaU0lzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwcmRXSmxMWE41YzNSbGJUcGhjbWR2WTJRdGJXRnVZV2RsY2lKOS5xSmxLYm9EbGE2Nm01R1g3a3BKajhvSGIzQ2tpbG1xcjFadGhsMHZPc0FGWjBXM2hSUl9scGVrQ3F5d1hORjFxcE5JMTlQSjhDTVVRZmdsZVV4YjRxc2s4NzRhZnhSZV9PaFJJVEtXRDRuN2k4MnZNY0JwTmNxalBYQXZFeThRN0pxQWpRYjlNMUxUQ2NjUWtxdTRkMzFTSHFxZUdTWDRHdTVsMXB3clp3WEJDZUcxdmVwQ3VaNVI3SU1lSmFNVlpDTVFWTy1hOG10OW1GLVpXQmJiRkJXa0w0Um1ab0JGRUphQW5TSW5sdGV3ckhkanJhWHNyQ1lLRy1DS1p4X2gtdDdUVDJMUzZqQ2dNUE9hWkNSbW9Nc191RVV3Sm1KRzhLNm9Mb1lXNFFtbDVRQTVuTWhOLTExRUF3QUdSN0xkUW8tbW0tZjBRZERpN09BeUpwM1NqQmciLCJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlLCJjYURhdGEiOiJMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VONVJFTkRRV0pEWjBGM1NVSkJaMGxDUVVSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRldUVkpOZDBWUldVUldVVkZFUlhkd2NtUlhTbXdLWTIwMWJHUkhWbnBOUWpSWVJGUkpkMDFFUlhkUFJFRjVUVVJCZVU1c2IxaEVWRTEzVFVSRmQwNVVRWGxOUkVGNVRteHZkMFpVUlZSTlFrVkhRVEZWUlFwQmVFMUxZVE5XYVZwWVNuVmFXRkpzWTNwRFEwRlRTWGRFVVZsS1MyOWFTV2gyWTA1QlVVVkNRbEZCUkdkblJWQkJSRU5EUVZGdlEyZG5SVUpCVGtrNENtcFBTUzlMVEVoT1ptaHdhRGRGWW5KSmNXbDBUVWRTV0V0Vk5rVTVaR0Y2WkhRMk1tUXdNV0pKTjBReGJsUXhZbUpEZVdkQ2EyRnRRalpTWWpCUFdtWUtkMDgzU1ZOTlVYcGxXbTUyVGtaMmFVRmpXbUpPVVhKdVltVXlkRkJhYzNCQ1RtNDJhR2R6U0ZCcmRWTnJkRWxrZUhOVVVHSXZNR2h3YTFCWFFtcE9kQXBwUlRsemVVZG1jVEl3U2tzMk9IVlRkakpJZWtrd2FUUjJaSGxzV214NlN6WlpTRTF1VXpablFuaFlSa2szV25WU056RmFlRzA0VTNkRWVEVmlURFl5Q25oaFNHOW9iMFkzWTBkSVpsTklOeloyUTBOT1NqRlRVSFJXZWxSemREbDVOa2RqVUVzME9VeGpUR3B5VVRFeFptMWxjQzlRTkRKYU1rZEZUbVYyU1dZS1pURkRkak0zWlhKMlVTdEtlbTVWT0ZCeE1XVnBiVk0wVFhvMU5VaDZZMmxRWnpNemFuZzFkMXB0U2twb1ZYb3dZakkzU0RaTk5WZGpLemRtU2prMlNncE1SM0ZpT1c5MWRIVkNlR3haYTFaVVZuWk5RMEYzUlVGQllVMXFUVU5GZDBSbldVUldVakJRUVZGSUwwSkJVVVJCWjB0clRVRTRSMEV4VldSRmQwVkNDaTkzVVVaTlFVMUNRV1k0ZDBSUldVcExiMXBKYUhaalRrRlJSVXhDVVVGRVoyZEZRa0ZHUzA5MlJqRkxja3B2ZVdoM1NEQkJibU5tVTBRM2VqRXJSRzhLV0UxTVdXVlJiV2RaYlcxeFVubHdjVW8wVHpoU1VISTRWMDFRWkRoTVVWQTNaVlJaYUhkdWJIZEhkR1J6UlVWS1ZtTlNSRFpOYlZONmNtZE5XalUyZUFwT0t6SkpXa2xQWm01R00xUlViWEJZYkhObE1VZzROSFZ5VlhGNlJUTjZlSEprYWxob2FHNVRUbGs0TDNwdmFHWTFOVE54V1VVNFQwOHZZVXAwWXpSYUNrbEZiekZ1ZGpsNGVHWXdkVWxoTDBaclEzQk1VQzlXTm5OaWRYTm1abkJ1Um01bUszSnFZM0Z0VEhaS2FteGFNbVZDUTJnd09FZERkRGh1UVVsSVluWUthVVZyVDA1M2VrRXZTbVJVY21Rdk1VSk1jME5DYjI1NWRYcGFWbXQyTVU0ME1sSTVjRGxFUXpSeFZXZFJVMUJ0Um05b1NETkZXblZ4YjJkalFsRjZZZ3AxY1ZCWWJrSXdaVEk1VmxGeVpuTlpVRGRGUlZNMFRFRm9VM0JwTWxsU2Iyd3Zabm8wV21oTVVXTmFibEZsUnpGRmNqQkVhVFZDWm1nNWJ6MEtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJWRVV0TFMwdExRbz0ifX0=
  name: ZG9ja2VyLWRlc2t0b3A=
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRvY2tlci5pbnRlcm5hbDo2NDQz
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: cluster-kubernetes.docker.internal-904396332
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: springboot-web-dev
spec:
  description: springboot sample web
  destinations:
  - namespace: springboot-web-dev
    server: https://kubernetes.docker.internal:6443
  sourceRepos:
  - https://github.com/yoonyeoseong/kubernetes-sample.git
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-web-dev
spec:
  destination:
    namespace: springboot-web-dev
    server: https://kubernetes.docker.internal:6443
  project: springboot-web-dev
  source:
    path: deploy/dev
    repoURL: https://github.com/yoonyeoseong/kubernetes-sample.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
status:
  health:
    status: Healthy
  history:
  - deployStartedAt: "2020-08-30T11:38:41Z"
    deployedAt: "2020-08-30T11:38:42Z"
    id: 0
    revision: dc44877971e21a464e30c5bedfcc82558d4bed5c
    source:
      path: deploy/dev
      repoURL: https://github.com/yoonyeoseong/kubernetes-sample.git
      targetRevision: HEAD
  observedAt: "2020-08-30T12:08:00Z"
  operationState:
    finishedAt: "2020-08-30T11:38:42Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: dc44877971e21a464e30c5bedfcc82558d4bed5c
    phase: Succeeded
    startedAt: "2020-08-30T11:38:41Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/springboot-web-service created
        name: springboot-web-service
        namespace: springboot-web-dev
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/springboot-app-deployment created
        name: springboot-app-deployment
        namespace: springboot-web-dev
        status: Synced
        syncPhase: Sync
        version: v1
      - group: extensions
        hookPhase: Running
        kind: Ingress
        message: ingress.extensions/springboot-web-ingress created
        name: springboot-web-ingress
        namespace: springboot-web-dev
        status: Synced
        syncPhase: Sync
        version: v1beta1
      revision: dc44877971e21a464e30c5bedfcc82558d4bed5c
      source:
        path: deploy/dev
        repoURL: https://github.com/yoonyeoseong/kubernetes-sample.git
        targetRevision: HEAD
  reconciledAt: "2020-08-30T12:08:00Z"
  resources:
  - health:
      status: Healthy
    kind: Service
    name: springboot-web-service
    namespace: springboot-web-dev
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: springboot-app-deployment
    namespace: springboot-web-dev
    status: Synced
    version: v1
  - group: extensions
    health:
      status: Healthy
    kind: Ingress
    name: springboot-web-ingress
    namespace: springboot-web-dev
    status: Synced
    version: v1beta1
  sourceType: Kustomize
  summary:
    externalURLs:
    - http://levi.local.com/
    images:
    - 1223yys/springboot-web:latest
  sync:
    comparedTo:
      destination:
        namespace: springboot-web-dev
        server: https://kubernetes.docker.internal:6443
      source:
        path: deploy/dev
        repoURL: https://github.com/yoonyeoseong/kubernetes-sample.git
        targetRevision: HEAD
    revision: dc44877971e21a464e30c5bedfcc82558d4bed5c
    status: Synced
---
