apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-web
  template:
    metadata:
      labels:
        app: springboot-web
    spec:
      containers:
        - name: springboot-web
          image: 1223yys/springboot-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-dev
                  key: WEP-APP-PORT
          livenessProbe:
            httpGet:
              port: 9090
              path: /api
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              port: 9090
              path: /api
            initialDelaySeconds: 20