apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-sample
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: sample-service
          servicePort: 80
