apiVersion: v1
kind: Service
metadata:
  name: springboot-web-service
  namespace: springboot-app
spec:
  selector:
    app: springboot-web
  ports:
    - name: http
      port: 80
      targetPort: 9090